export default [
  {
    id: 1,
    name: "Test Whatsapp",
    region: "US",
    campaignData: 1559807714999,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: "/assets/thumb1.png",
  },
  {
    id: 2,
    name: "Super Jewels Quest",
    region: "CA, FR",
    campaignData: 1559806715124,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: "/assets/thumb2.png",
  },
  {
    id: 3,
    name: "Mole Slayer",
    region: "FR",
    campaignData: 1559806711124,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: "/assets/thumb3.png",
  },
  {
    id: 4,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1559806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb4.png",
  },
  {
    id: 5,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1559806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb5.png",
  },
  {
    id: 6,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1559806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb6.png",
  },
  {
    id: 7,
    name: "Test Whatsapp",
    region: "US",
    campaignData: 1559807714999,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: "/assets/thumb1.png",
  },
  {
    id: 8,
    name: "Super Jewels Quest",
    region: "CA, FR",
    campaignData: 1559806715124,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: "/assets/thumb2.png",
  },
  {
    id:9,
    name: "Mole Slayer",
    region: "FR",
    campaignData: 1559806711124,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: "/assets/thumb3.png",
  },
  {
    id: 10,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1559806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb4.png",
  },
  {
    id: 11,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1559806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb5.png",
  },
  {
    id: 12,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1559806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb6.png",
  },
  {
    id: 13,
    name: "Test Whatsapp",
    region: "US",
    campaignData: 1559807714999,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: "/assets/thumb1.png",
  },
  {
    id: 14,
    name: "Super Jewels Quest",
    region: "CA, FR",
    campaignData: 1625994816622,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: "/assets/thumb2.png",
  },
  {
    id: 15,
    name: "Mole Slayer",
    region: "FR",
    campaignData: 1625994816622,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: "/assets/thumb3.png",
  },
  {
    id: 16,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1625995016622,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb4.png",
  },
  {
    id: 17,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1625994916622,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb5.png",
  },
  {
    id: 18,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1625994817622,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb6.png",
  },
  {
    id: 19,
    name: "Test Whatsapp",
    region: "US",
    campaignData: 1625994816622,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: "/assets/thumb1.png",
  },
  {
    id: 20,
    name: "Super Jewels Quest",
    region: "CA, FR",
    campaignData: 1625994816622,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: "/assets/thumb2.png",
  },
  {
    id: 21,
    name: "Mole Slayer",
    region: "FR",
    campaignData: 1625994816622,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: "/assets/thumb3.png",
  },
  {
    id: 22,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1625994816622,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb4.png",
  },
  {
    id: 23,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1859806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb5.png",
  },
  {
    id: 24,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1859806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb6.png",
  },
  {
    id: 25,
    name: "Test Whatsapp",
    region: "US",
    campaignData: 1659807714999,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: "/assets/thumb1.png",
  },
  {
    id: 26,
    name: "Super Jewels Quest",
    region: "CA, FR",
    campaignData: 1659806715124,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: "/assets/thumb2.png",
  },
  {
    id: 27,
    name: "Mole Slayer",
    region: "FR",
    campaignData: 1659806711124,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: "/assets/thumb3.png",
  },
  {
    id: 28,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1659806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb4.png",
  },
  {
    id: 29,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1659806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb5.png",
  },
  {
    id: 30,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1659806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb6.png",
  },
  {
    id: 31,
    name: "Test Whatsapp",
    region: "US",
    campaignData: 1659807714999,
    price: "Price info of Test Whatsapp",
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: "/assets/thumb1.png",
  },
  {
    id: 32,
    name: "Super Jewels Quest",
    region: "CA, FR",
    campaignData: 16459806715124,
    price: "Price info of Super Jewels Quest",
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: "/assets/thumb2.png",
  },
  {
    id: 33,
    name: "Mole Slayer",
    region: "FR",
    campaignData: 1659806711124,
    price: "Price info of Mole Slayer",
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: "/assets/thumb3.png",
  },
  {
    id: 34,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1659806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb4.png",
  },
  {
    id: 35,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1659806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb5.png",
  },
  {
    id: 36,
    name: "Mancala Mix",
    region: "JP",
    campaignData: 1659806680124,
    price: "Price info of Mancala Mix",
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "/assets/thumb6.png",
  },
];
